# Generated by Django 4.2.3 on 2023-08-02 06:14

import datetime
from django.db import migrations, models
import receipts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receipts',
            fields=[
                ('receipt_Date', models.DateField(default=datetime.date(2023, 4, 1), help_text='Please use the following format: <em>DD-MM-YYYY</em>.', validators=[receipts.models.Validate_DateRange], verbose_name='Receipt Issue Date')),
                ('receipt_Id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_No', models.CharField(help_text='Receipt or Invoice Number', max_length=20, verbose_name='Receipt Number')),
                ('receipt_Name', models.CharField(help_text='Receipt Description', max_length=100, verbose_name='Receipt Name')),
                ('receipt_Amount', models.PositiveIntegerField(help_text='Receipt Amount in Rs Ps > 0', verbose_name='Receipt Amount')),
            ],
            options={
                'ordering': ['receipt_Date'],
            },
        ),
    ]
